version: 2

models:
  - name: test_urls
    tests:
      - assert_equal:
          actual: actual
          expected: expected
          
models:
  - name: test_url_host
    tests:
      - assert_equal:
          actual: actual
          expected: expected