
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch
      - image: circleci/postgres:9.6.5-alpine-ram

    steps:
      - checkout

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv venv
            . venv/bin/activate

            # Temporary fix for 0.11.0 bug -- 0.11.1 is yet unreleased
            # TODO : Make this use latest from pip once 0.11.1 is out
            git clone https://github.com/fishtown-analytics/dbt.git
            cd dbt
            git checkout dev/lucretia-mott
            pip install -e .
            cd ..

            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run tests (postgres)"
          environment:
            CI_DBT_USER: root
            CI_DBT_PASS: ''
            CI_DBT_PORT: 5432
            CI_DBT_DBNAME: circle_test
          command: |
            . venv/bin/activate
            cd integration_tests
            dbt deps
            dbt seed
            dbt run
            dbt test

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
